server:
  port: 7896
  servlet:
    context-path: /order-server

spring:
  application:
    name: order-server
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/seata-at-test1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 200
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-error-retry-attempts: 3
      break-after-acquire-failure: true
      time-between-connect-error-millis: 300000
      async-init: true
      remove-abandoned: false
      remove-abandoned-timeout-millis: 1800
      transaction-query-timeout: 6000
      #filter-class-names: stat,wall,log4j2
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        allow:
        deny:
        reset-enable: false # 是否允许重置数据
        login-username: admin
        login-password: admin
        enabled: true
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
feign:
  hystrix:
    enabled: true
