server:
  port: 7897

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seata-at-test1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
