server:
  servlet:
    context-path: /user-server
    encoding:
      force: true
      charset: utf-8

spring:
  boot:
    admin:
      client:
        url: http://192.168.31.143:5897/admin-server
        instance:
          name: user-server
          prefer-ip: true
        username: admin
        password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/seata-at-test3
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 200
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-error-retry-attempts: 3
      break-after-acquire-failure: true
      time-between-connect-error-millis: 300000
      async-init: true
      remove-abandoned: false
      remove-abandoned-timeout-millis: 1800
      transaction-query-timeout: 6000
      #filter-class-names: stat,wall,log4j2
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        allow:
        deny:
        reset-enable: false # 是否允许重置数据
        login-username: admin
        login-password: admin
        enabled: true
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml

feign:
  hystrix:
    enabled: true
  seata:
    enabled: true

jwt:
  secret: 2uKsDY4mPnXL3zHd4YNs+ke6dLQ9XcHHzakpxjMBt+Gr8AMILn5yeKDP5EcbIEUXuqBV3X7RliXlH+e5l3i4gA==
  expiration: 3600

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  file:
    name: /Users/renyuanxin/logs/user-server.log
